### ISSUE TITLE
setExternalUserId() works randomly on iOS

### ISSUE THREAD

**Issue by enricobenedos** [OneSignal/OneSignal-Flutter-SDK#150] opened 2019-10-04 09:46 UTC
**Description:**

`setExternalUserId()` sometimes does not set the `external_user_id` on iOS. Retrying sometimes solve this issue and the `external_user_id` is correctly set. 

In the next screenshot you can see that the iPhone9,3 was not able to setUserExternalId() after notifications subscribe:

![image](https://user-images.githubusercontent.com/12233746/66198285-5f51e500-e69c-11e9-8295-0337cb2b725b.png)

**Environment**

I'm using `Flutter 1.9.1+hotfix.4` and `onesignal_flutter: ^2.1.0`

**Steps to Reproduce Issue:**

1. 
```
OneSignal.shared.init(appId, iOSSettings: {
      OSiOSSettings.autoPrompt: true,
      OSiOSSettings.inAppLaunchUrl: true
    });
```
2.
```
OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);
```
3.
```
bool _requiresConsent = await OneSignal.shared.requiresUserPrivacyConsent();
```
4.
 ```
await OneSignal.shared.consentGranted(true);
        //Set subscription
        OneSignal.shared.setSubscription(true);
```
5.
```
static Future<void> setSpecificUserId(String userId) async {
    await OneSignal.shared.setExternalUserId(userId);
  }
```

**Anything else:**

I'm using iOS 13.1.2 on iPad 2018 (6th gen)

**Comment by rgomezp** [comment] 2019-10-09 23:13
Thanks for your patience while we investigate

**Comment by enricobenedos** [comment] 2019-10-11 07:50
@rgomezp sorry, but I think it is my problem. Sometimes I call `removeExternalUserId()` and `setExternalId()` before privacy consent requiring
```log
W/OneSignal( 8432): Method removeExternalUserId() was called before the user provided privacy consent. Your application is set to require the user's privacy consent before the OneSignal SDK can be initialized. Please ensure the user has provided consent before calling this method. You can check the latest OneSignal consent status by calling OneSignal.userProvidedPrivacyConsent()
W/OneSignal( 8432): Method setExternalId() was called before the user provided privacy consent. Your application is set to require the user's privacy consent before the OneSignal SDK can be initialized. Please ensure the user has provided consent before calling this method. You can check the latest OneSignal consent status by calling OneSignal.userProvidedPrivacyConsent()
```
Now I need to test my new code for some days then I can confirm you if this code error is the cause of my problem

**Comment by enricobenedos** [comment] 2019-10-11 11:32
At the moment I'm trying to refactor my code but I have a problem related to the fact that `OneSignal.userProvidedPrivacyConsent()` does not exist

**Comment by rgomezp** [comment] 2019-10-21 23:14
Thanks for your update. Were you able to resolve?

**Comment by enricobenedos** [comment] 2019-10-22 06:24
At the moment no, the same code on Android works perfectly (tested with a lot of devices of different manufacturer) but on iOS it often does not work. It happen that the device subscribe correctly to notifications but the external user id is set randomly. 
In the free time I'm trying to write a test app to show you this behavior but at the moment I'm very busy.

About `OneSignal.userProvidedPrivacyConsent()` have you got any info? Is it a removed method missed in the docs?

**Comment by rgomezp** [comment] 2019-11-07 23:51
That method does not exist in the Flutter SDK. Please let us know when you come up with a repro app

**Comment by rgomezp** [comment] 2019-11-19 02:18
Closing due to no response

**Comment by chrisparkeronline** [comment] 2020-04-09 03:25
I am having this same problem. Works all the time in Android, but iOS some of the time. Usually works after repeated calls of SetExternalUserId. I am using Xamarin and not Flutter. My code is simple. I do not call the RemoveExternalUserId at all.

Additionally the call SendTags works every single time on both Android and iOS. I have tried using the UserDidProviderPrivacyConsent(true) and that doesn't solve the problem.

**Comment by chrisparkeronline** [comment] 2020-04-09 03:51
Check the logs I get the following message.
WARNING: Attempted to set external user id, but [id] is already set

It appears the call only lets one device have the external id. However this is an issue because the app can be used on multiple devices and we wish to notify all devices associated with that account using that accounts external id.

Any help would be greatly appreciated.

**Comment by rgomezp** [comment] 2020-04-09 18:11
Howdy Chris,
You should really think of `external_id` as a "device id." The best way to get around this would be with one of the following:

> 1 - Add Data Tags or Filters to the user with some identifier, like their email or username.
> 2 - Use the setExternalUserId method to add your unique external_user_ids to the device
> 3 - Track the OneSignal player or external ids for each device on your own database. More details in Internal Database & CRM to keep track of Player IDs or External User Ids.

source: https://documentation.onesignal.com/docs/users#section-managing-one-user-on-multiple-devices

I hope this helps. Enjoy!

**Comment by mikechoch** [comment] 2020-04-10 19:35
@enricobenedos & @chrisparkeronline 

Are you using `setExternalUserId` or `removeExternalUserId` with in combo with our `setEmail` method?

Also we now offer `setExternalUserId` and `removeExternalUserId` with a callback. You should use this instead of making multiple calls to set and remove methods.

**Example for new callback:**
```
String externalUserId = "123456789";
OneSignal.shared.setExternalUserId().then((results) {
    if (results == null) return;
    // Now use the results of the call for each channel (push and email)
});
```

The newest Flutter SDK is `2.4.0`

**Comment by chrisparkeronline** [comment] 2020-04-11 01:00
Hi @mikechoch 
Using the Xamarin Forms SDK setExternalUserId callback version of the method seems to work for me. Thanks for the help.

**Comment by enricobenedos** [comment] 2020-05-20 12:39
hey @mikechoch, sorry for late response but no, I'm not using `setEmail` method. At the moment the project I was develop has been stopped. At the moment I'm experiencing a similar issue with a new project using simply `await OneSignal.shared.setSubscription()`. At the moment I'm a little bit frustrated with this library. There are a lot of behaviour difference between iOS and Android, and the official documentation sometimes is not updated due to the closed GitHub issues

**Comment by gilthonweapps** [comment] 2021-04-15 19:08
Hi, issue still there on version 3.0.0-beta2

**Comment by emawby** [comment] 2021-04-23 18:37
@gilthonweapps Hello, I am having trouble reproducing this issue. Are you able to provide some details around when you are calling setExternalUserId and what you are seeing on the dashboard?

**Comment by emawby** [comment] 2021-08-31 17:13
Closing this for now. If you are still experiencing this issue please reopen

**Closed by emawby** 2021-08-31 17:13 UTC
Labels: Help Wanted, Possible Bug

**Comment by rosscdh** [comment] 2021-11-02 10:14
+1 still present

**Comment by nmarko91** [comment] 2021-11-10 17:02
+1, sometimes works after first try sometimes does not work after a couple of tries

**Comment by VKladov** [comment] 2021-11-11 05:17
I had same issue but only in first app launch. Solve it by calling `setExternalUserId` after `subscriptionObserver` event call

**Comment by MursiDirect** [comment] 2022-11-29 23:32
I have the same issue here, any solution yet?
