### ISSUE TITLE
Flutter's v1 Android embedding to v2,

### ISSUE THREAD

**Issue by sumitgohil** [OneSignal/OneSignal-Flutter-SDK#216] opened 2020-03-07 22:48 UTC
Hello, I wanted to know if this plugin has Migrated to Flutter Android Embedding to v2. I still get error mentioned in this issue #190

**Comment by rgomezp** [comment] 2020-04-29 21:10
Duplicate of #190

**Closed by rgomezp** 2020-04-29 21:10 UTC
Labels: Enhancement/Feature
