### ISSUE TITLE
Actually am using onesignal and firebase_auth on same app getting app crash

### ISSUE THREAD

**Issue by sivapictuscode** [OneSignal/OneSignal-Flutter-SDK#155] opened 2019-10-10 09:28 UTC
**Description:**
I used both onesignal and firebase_auth based google login, if i initialize onesingal it return token after that getting below error

Rejecting re-init on previously-failed class java.lang.Class: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.seek-Aq7q4Ly6HVEDPPreJQc1zQ==/base.apk!classes2.dex) I/zygote64(30113): at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)

**Environment**
cupertino_icons: ^0.1.2
scoped_model: "^0.3.0"
http: ^0.12.0+2
lazy_load_scrollview: ^1.0.0
sqflite: any
path_provider: any
icon_shadow: ^1.0.1
flutter_responsive_screen: ^1.0.0
shared_preferences: ^0.5.3+4
connectivity: ^0.4.3+6
flutter_range_slider: ^1.3.1
image_cropper: ^1.0.2
image_picker: ^0.6.1+3
url_launcher: ^5.1.2
rich_alert: ^0.1.32
flutter_svg: ^0.14.1
google_sign_in: ^4.0.7
date_picker_timeline: ^0.0.3
smooth_star_rating: ^1.0.3
date_format: ^1.0.6
flutter_google_places: ^0.2.3
flutter_masked_text: ^0.8.0
flutter_facebook_login: ^3.0.0
firebase_auth: ^0.14.0+5
onesignal_flutter: ^2.1.0

**Steps to Reproduce Issue:**
if i run app it return a onesignal token after that app crash

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment] 2019-10-11 21:58
Duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/754

**Closed by rgomezp** 2019-10-11 21:58 UTC
