### ISSUE TITLE
In-app message crashes Android app when notification tapped

### ISSUE THREAD

**Issue by vtisnado** [OneSignal/OneSignal-Flutter-SDK#264] opened 2020-06-30 06:04 UTC
**Description:**

When I configure a In-app message, I can see the notification in the Android tray, but, when tapped to see the message, the app stop working.

Here is the console error:

```
I/WebViewFactory(27090): Loading com.google.android.webview version 83.0.4103.106 (code 410410650)
I/cr_LibraryLoader(27090): Loaded native library version number "83.0.4103.106"
I/cr_CachingUmaRecorder(27090): Flushed 3 samples from 3 histograms.
E/chromium(27090): [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/APP_PATH/cache/WebView/Crashpad: No such file or directory (2)
E/libEGL  (27090): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
W/cr_media(27090): Requires BLUETOOTH permission
W/VideoCapabilities(27090): Unrecognized profile 2130706433 for video/avc
W/AudioCapabilities(27090): Unsupported mime audio/alac
W/AudioCapabilities(27090): Unsupported mime audio/dsd
W/VideoCapabilities(27090): Unsupported mime video/divx
W/VideoCapabilities(27090): Unsupported mime video/divx311
W/VideoCapabilities(27090): Unsupported mime video/divx4
W/VideoCapabilities(27090): Unsupported mime video/mp4v-esdp
I/VideoCapabilities(27090): Unsupported profile 4 for video/mp4v-es
E/chromium(27090): [ERROR:tile_manager.cc(793)] WARNING: tile memory limits exceeded, some content may not draw
E/chromium(27090): [ERROR:tile_manager.cc(793)] WARNING: tile memory limits exceeded, some content may not draw
E/chromium(27090): [ERROR:tile_manager.cc(793)] WARNING: tile memory limits exceeded, some content may not draw
E/chromium(27090): [ERROR:tile_manager.cc(793)] WARNING: tile memory limits exceeded, some content may not draw
I/chromium(27090): [INFO:CONSOLE(48)] "postMessageToNative(): {"type":"rendering_complete","pageMetaData":{"rect":{"height":448.66668701171875},"flexContainerRect":{"x":24,"y":24,"width":264,"height":472,"top":24,"right":288,"bottom":496,"left":24}},"displayLocation":"center_modal"}", source: data:text/html; charset=utf-8;base64,PGh0bWw+CjxoZWFkPjxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wLCBtYXhpbXVtLXNjYWxlPTEuMCwgdXNlci1zY2FsYWJsZT1ubyIvPgo8c3R5bGU+CiAgICAqIHsKICAgICAgICAtd2Via2l0LXRvdWNoLWNhbGxvdXQ6IG5vbmU7CiAgICAgICAgLXdlYmtpdC11c2VyLXNlbGVjdDogbm9uZTsgLyogRGlzYWJsZSBzZWxlY3Rpb24vY29weSBpbiBVSVdlYlZpZXcgKi8KICAgIH0KICAgIGgxIHsKICAgICAgICBmb250LXdlaWdodDogNDAwOwogICAgfQogICAgYm9keSB7CiAgICAgICAgZm9udC1mYW1pbHk6IC1hcHBsZS1zeXN0ZW0sQmxpbmtNYWNTeXN0ZW1Gb250LCJTZWdvZSBVSSIsUm9ib3RvLE94eWdlbi1TYW5zLFVidW50dSxDYW50YXJlbGwsIkhlbHZldGljYSBOZXVlIixzYW5zLXNlcmlmOwogICAgICAgIHBhZGRpbmc6IDE2cHg7CiAgICAgICAgb3ZlcmZsb3c6IGhpZGRlbjsKICAgICAgICBjdXJzb3I6IHBvaW50ZXI7YmFja2dyb3VuZC1jb2xvcjogI0ZGRkZGRjsKICAgICAgICAKICAgIH0KCiAgICAuZmxleC1jb250YWluZXIgewogICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsKICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICB9CgogICAgLyogdG9wIGxldmVsIGVsZW1lbnRzICovCiAgICAuZmxleC1jb250YWluZXIgPiAqIHsKICAgICAgICBtYXJnaW4tdG9wOiA4cHg7CiAgICAgICAgbWFyZ2luLWJvdHRvbTogOHB4OwogICAgfQoKICAgIC8qIEltYWdlIG9ubHkgZm9yIEZ1bGxzY3JlZW4gYW5kIE1vZGFsICovCiAgICAuaW1hZ2UtY29udGFpbmVyIHsKICAgICAgICBkaXNwbGF5OiBmbGV4OwogICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICB9Cjwvc3R5bGU+CjxzY3JpcHQ+CiAgICAvLyBDYWxsZWQgZnJvbSBvbkNsaWNrIG9mIGltYWdlcywgYnV0dG9ucywgYW5kIGRpc21pc3MgYnV0dG9uCiAgICBmdW5jdGlvbiBhY3Rpb25UYWtlbihkYXRhLCBjbGlja1R5cGUpIHsKICAgICAgICBjb25zb2xlLmxvZygiYWN0aW9uVGFrZW4oKTogIiArIEpTT04uc3RyaW5naWZ5KGRhdGEpKTsKICAgICAgICBpZiAoY2xpY2tUeXBlKQogICAgICAgICAgICBkYXRhWyJjbGlja190eXBlIl0gPSBjbGlja1R5cGU7CiAgICAgICAgcG9zdE1lc3NhZ2VUb05hdGl2ZSh7IHR5cGU6ICJhY3Rpb25fdGFrZW4iLCBib2R5OiBkYXRhIH0pOwogICAgfQoKICAgIGZ1bmN0aW9uIHBvc3RNZXNzYWdlVG9OYXRpdmUobXNnSnNvbikgewogICAgICAgIGNvbnNvbGUubG9nKCJwb3N0TWVzc2FnZVRvTmF0aXZlKCk6ICIgKyBKU09OLnN0cmluZ2lmeShtc2dKc29uKSk7CiAgICAgICAgdmFyIGVuY29kZWRNc2cgPSBKU09OLnN0cmluZ2lmeShtc2dKc29uKTsKICAgICAgICBwb3N0TWVzc2FnZVRvSW9zKGVuY29kZWRNc2cpOwogICAgICAgIHBvc3RNZXNzYWdlVG9BbmRyb2lkKGVuY29kZWRNc2cpOwogICAgICAgIHBvc3RNZXNzYWdlVG9EYXNoYm9hcmQoZW5jb2RlZE1zZyk7CiAgICB9CgogICAgZnVuY3Rpb24gcG9zdE1lc3NhZ2VUb0lvcyhlbmNvZGVkTXNnKSB7CiAgICAgICAgLy8gU2VlIGlPUyBTREsgU291cmNlCiAgICAgICAgLy8gICAgdXNlckNvbnRlbnRDb250cm9sbGVyOmRpZFJlY2VpdmVTY3JpcHRNZXNzYWdlOgogICAgICAgIGlmICh3aW5kb3cud2Via2l0ICYmIHdpbmRvdy53ZWJraXQubWVzc2FnZUhhbmRsZXJzICYmIHdpbmRvdy53ZWJraXQubWVzc2FnZUhhbmRsZXJzLmlvc0xpc3RlbmVyKQogICAgICAgICAgICB3aW5kb3cud2Via2l0Lm1lc3NhZ2VIYW5kbGVycy5pb3NMaXN0ZW5lci5wb3N0TWVzc2FnZShlbmNvZGVkTXNnKTsKICAgIH0KCiAgICBmdW5jdGlvbiBwb3N0TWVzc2FnZVRvQW5kcm9pZChlbmNvZGVkTXNnKSB7CiAgICAgICAgaWYgKHdpbmRvdy5PU0FuZHJvaWQpCiAgICAgICAgICAgIHdpbmRvdy5PU0FuZHJvaWQucG9zdE1lc3NhZ2UoZW5jb2RlZE1zZyk7CiAgICB9CgogICAgZnVuY3Rpb24gcG9zdE1lc3NhZ2VUb0Rhc2hib2FyZChlbmNvZGVkTXNnKSB7CiAgICAgICAgaWYgKHdpbmRvdy5wYXJlbnQpIHsKICAgICAgICAgICAgd2luZG93LnBhcmVudC5wb3N0TWVzc2FnZShlbmNvZGVkTXNnLCAiKiIpOwogICAgICAgIH0KICAgIH0KCiAgICAvLyBsYXN0LWVsZW1lbnQgbmVlZGVkIHRvIGdpdmUgdGhlIGNvcnJlY3QgaGVpZ2h0IGZvciBtb2RhbHMgYW5kIGJhbm5lcnMKICAgIGZ1bmN0aW9uIGdldFBhZ2VNZXRhRGF0YSgpIHsKICAgICAgICB2YXIgbGFzdEVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgibGFzdC1lbGVtZW50Iik7CiAgICAgICAgaWYgKCFsYXN0RWxlbWVudCkKICAgICAgICAgICAgcmV0dXJuIHt9OwoKICAgICAgICB2YXIgZmxleENvbnRhaW5lciA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIi5mbGV4LWNvbnRhaW5lciIpOwogICAgICAgIGlmICghZmxleENvbnRhaW5lcikgewogICAgICAgICAgICBjb25zb2xlLmVycm9yKCJDb3VsZCBub3QgZmluZCBmbGV4LWNvbnRhaW5lciBjbGFzcyByZXF1aXJlZCB0byByZXNpemUgbW9kYWwgY29ycmVjdGx5ISIpOwogICAgICAgICAgICByZXR1cm4ge307CiAgICAgICAgfQoKICAgICAgICAvLyByZWN0Lnkgd2lsbCBiZSB1bmRlZmluZWQgb24gQW5kcm9pZCA0LjQKICAgICAgICB2YXIgZmxleENvbnRhaW5lclJlY3QgPSBmbGV4Q29udGFpbmVyLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpOwogICAgICAgIHJldHVybiB7CiAgICAgICAgICAgIHJlY3Q6IHsKICAgI
E/chromium(27090): [ERROR:tile_manager.cc(793)] WARNING: tile memory limits exceeded, some content may not draw
E/chromium(27090): [ERROR:tile_manager.cc(793)] WARNING: tile memory limits exceeded, some content may not draw
E/OpenGLRenderer(27090): resultIndex is -1, the polygon must be invalid!
F/libc    (27090): Fatal signal 11 (SIGSEGV), code -6, fault addr 0x69d2 in tid 30560 (hwuiTask1)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
UUID: 94003fb8-1f01-462d-9a79-9f640c3c3cee
Build fingerprint: 'Sony/D6603/D6603:6.0.1/23.5.A.1.291/2769308465:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 27090, tid: 30560, name: hwuiTask1  >>> APP_BUNDLE_ID <<<
signal 7 (SIGBUS), code -6 (SI_TKILL), fault addr 0xe2
    r0 00000027  r1 000000e5  r2 00000002  r3 000000e6
    r4 00000026  r5 00000102  r6 00000001  r7 7e73ecf0
    r8 00000025  r9 7e73e070  sl 7e73f078  fp 000000de
    ip 7e73ee74  sp 000000e3  lr 0000001f  pc b5d43690  cpsr 000f0030
backtrace:
    #00 pc 0005a690  /system/lib/libhwui.so
    #01 pc 0000000d  <unknown>
Tombstone written to: /data/tombstones/tombstone_08
```

**Environment**

Flutter Doctor result:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
```

**Steps to Reproduce Issue:**

  1. Create a new In-app message and send to a test device
  2. Tap the notification to see the in app message

**Anything else:**

Not tested in iPhone yet.

**Comment by rgomezp** [comment] 2020-07-01 19:17
Duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/930

**Closed by rgomezp** 2020-07-01 19:17 UTC
