### ISSUE TITLE
Android app not launch sometimes when i touch the notification.

### ISSUE THREAD

**Issue by GeceGibi** [OneSignal/OneSignal-Flutter-SDK#462] opened 2021-08-11 07:40 UTC
**Description:**

Title explains the problem.

**Environment**

SDK Version: 3.2.0
SDK Added from Pub

**Steps to Reproduce Issue:**

1. App open 
2. Press android home button or go home screen. (○ button )
3. Send Notification to device.
4. Close app manually from android app control screen ( ▢ button )
5. Touch the notification

**Anything else:**

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1151], locale en-US)
    • Flutter version 2.2.3 at D:\Flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\\####\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\\####\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\\####\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

• No issues found!

**Comment by jkasten2** [comment] 2021-08-12 00:58
@GeceGibi Thanks for reporting. Could you provide the following details?
1. Android Version(s)
2. Device Model(s)
3. Also any Android version and device models you don't see the issue on are useful too
4. Does the issue only happen when you "4. Close app manually from android app control screen ( ▢ button )"?
5. Could you share you logcat as an attached .txt / .log file?
    * Note when you swipe away the app in the log and when you open the notification too so we can find the right spot.
    
    
Also there are some upcoming changes that might improve or fix this issue I want to reference here:
* https://github.com/OneSignal/OneSignal-Android-SDK/pull/1377

**Comment by GeceGibi** [comment] 2021-08-12 10:41
1-2-3 : 
This bug happening every time with this device:
`Redmi Note 9S (mobile) • 2f755042 • android-arm64  • Android 11 (API 30)`

I tried every posibilities wtih this device too and app worked as espected:
`JNY LX1 (mobile) • EPHUT20220023166 • android-arm64  • Android 10 (API 29) `

4: Nope, it's mean when notification comes up and app was closed for some reason maybe user do that maybe device energy save mode do that.

Yea, this pull request maybe resolve this issue.

**Comment by zeucxb** [comment] 2021-08-12 20:38
Same problem here.

**Comment by phucho236** [comment] 2021-08-13 07:22
> Same problem here.

try using navigatorKey

**Comment by GeceGibi** [comment] 2021-08-16 08:21
@phucho236 this reply is not about the issue..

**Comment by GeceGibi** [comment] 2021-08-24 10:27
@jkasten2 any changes ?

**Comment by emawby** [comment] 2021-08-24 16:48
@GeceGibi The [Reverse Activity Trampolining Implementation](https://github.com/OneSignal/OneSignal-Android-SDK/pull/1377) PR has been released on our Android Native SDK which will be a part of the next Flutter release which should come out shortly. Thank you for your patience!

**Comment by GeceGibi** [comment] 2021-08-25 08:24
I tried with latest(3.2.1) version but this issue not fixed.

**Comment by GeceGibi** [comment] 2021-08-28 11:42
I also tried with v3.2.2 but nothing changed.

**Comment by jkasten2** [comment] 2021-08-30 17:03
@GeceGibi Can you capture a full system logcat (verbose, without any filters) just before tapping on the notification to just after on the devices have issues?

@zeucxb Can you try the new 3.2.2 version? If you still see an issue please also provide the logcat noted above and the device models and Android versions you are seeing the issue on.

**Comment by GeceGibi** [comment] 2021-08-30 17:14
https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/464

I just waiting this pr. I think everything will be okey after this pr.

**Comment by efraespada** [comment] 2021-09-06 08:36
@GeceGibi you can test the PR with this:
```yaml
onesignal_flutter:
    git:
      url: https://github.com/efraespada/OneSignal-Flutter-SDK.git
```
Follow the PR #464 instructions.

**Comment by GeceGibi** [comment] 2021-09-06 14:04
> @GeceGibi you can test the PR with this:
> ```yaml
> onesignal_flutter:
>     git:
>       url: https://github.com/efraespada/OneSignal-Flutter-SDK.git
> ```
> Follow the PR #464 instructions.

Nah it's not working either. Notifications not coming up device when app closed.

I got roll back one signal version to 2.6.4 it's working fine right now.

**Comment by gumilar1995** [comment] 2021-09-20 16:20
Hi @jkasten2 ,

I'm facing same issue.
Here is my device detail : Redmi Note 7 (mobile) • c4eecc7e • android-arm64  • Android 10 (API 29)
I captured logcat of the system as you said from before tap the notification to 10s after issue occurs, you can see the log here : 
https://github.com/gumilar1995/files/blob/main/logcat.txt

**Comment by aryanyadav9** [comment] 2021-10-06 04:41
Hi @GeceGibi,
I am testing the Onesignal plugin on older android version (Nougat) and everything is working fine as expected. Looks like this issue is only on Android 10+ based devices. I am using Redmi Note 9 Pro where tapping on notification is not opening the app if the app is "just closed" (Removed from Recent App, Not force stopped). 
Most probably reason for app not getting launched could be either Android 10 or It's Redmi device (Higher Chances).

**Comment by GeceGibi** [comment] 2021-11-23 07:57
Crashlytics logs

```
OSNotificationRestoreWorkManager.java line 48
com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork
```


```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {net.memurlar/net.memurlar.MainActivity}: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4891)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4928)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

```
Caused by java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
       at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:156)
       at androidx.work.WorkManager.getInstance(WorkManager.java:184)
       at com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork(OSNotificationRestoreWorkManager.java:48)
       at com.onesignal.OneSignal.onAppFocusLogic(OneSignal.java:1390)
       at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1375)
       at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:182)
       at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:88)
       at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:91)
       at android.app.Application.dispatchActivityResumed(Application.java:455)
       at android.app.Activity.dispatchActivityResumed(Activity.java:1413)
       at android.app.Activity.onResume(Activity.java:1945)
       at io.flutter.embedding.android.FlutterActivity.onResume(FlutterActivity.java:569)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
       at android.app.Activity.performResume(Activity.java:8353)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4881)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4928)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by GeceGibi** [comment] 2021-11-28 11:04
@jkasten2 any update for this issue ?

**Comment by Makarov96** [comment] 2021-12-07 23:45
I have the same issue with the version   onesignal_flutter: ^3.2.7 any update?

**Comment by jkasten2** [comment] 2021-12-08 01:03
@GeceGibi @aryanyadav9 Can you try again with [onesignal_flutter 3.2.5](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.2.5) or newer? There was an Android regression bug mainly with notifications with Launch URL set (could have effect some other notifications).

Also just to confirm your message from before @GeceGibi, notification open is working correctly on your JNY LX1 device but not your Xiaomi Redmi Note 9S?

@GeceGibi @aryanyadav9 If you are only seeing an issue with Xiaomi devices can you post a reply with the information requested in [[Needs details from community] Xiaomi - Notification Open - Not foregrounding app](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1494)?

**Comment by j-ixcayau** [comment] 2021-12-08 14:41
I have the same issue with Xiaomi, Huawei and Sky devices.
This issue start after an migration of Flutter from 1 to 2.5, with the versions of One Signal that support Null safety

What I have noticed is that the package handle the push after on tap, is just that do not open the app

**Comment by GeceGibi** [comment] 2021-12-25 07:10
@jkasten2 I always use the latest version of onesignal and im using with strandart notification payload not with url.

Also device receives a notification, but the application does not open when touched.
The plugin was working fine in v2 but now I am not happy.

**Comment by aswinpraja** [comment] 2021-12-28 11:28
The issue is not reproducible with latest(3.2.7), let me know if anyone else is facing the same.

**Comment by Makarov96** [comment] 2022-01-04 17:59
any update about this issue? or someone has been able to fix ?

**Comment by ismailcaakir** [comment] 2022-01-07 20:57
I have same error in 3.2.7, 

Many users find this annoying. I can't re produce bug.

`onesignal_flutter:
    dependency: "direct main"
    description:
      name: onesignal_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.7"`

**Comment by GHO5TMEDO** [comment] 2022-01-12 08:45
I have the same issue with Xiaomi using latest onesignal_flutter.

**Comment by WaheedHussainHaans** [comment] 2022-01-18 19:48
Any updates on this facing same issue on redmi note 10 pro TIA

**Comment by renrael-yzal** [comment] 2022-01-20 05:24
Any Updates? facing same issue with Poco M2 Pro!

**Comment by tamirrab** [comment] 2022-01-20 09:43
Same here

**Comment by GeceGibi** [comment] 2022-01-20 11:42
> Any Updates? facing same issue with Poco M2 Pro!

Nopeee. They just watching us and do nothing. I'm waiting for six month.

**Comment by DavideArena** [comment] 2022-01-23 11:22
Same issue here with version 3.2.7 (i tried to update the version from 3.0.0 to 3.2.7, hoping for a fix, but problem is here yet), with android and xiaomi device, click on every notification doesn't open the app (with simple notification with launch url either)

**Comment by FeifanChang** [comment] 2022-01-25 10:42
same issue.

**Comment by mmustafaget** [comment] 2022-01-27 09:46
```
Caused by java.lang.IllegalStateException
WorkManager is not initialized properly. You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.

androidx.work.impl.WorkManagerImpl.a (WorkManagerImpl.java:36)
androidx.work.WorkManager.enqueue (WorkManager.java)
com.onesignal.OSNotificationRestoreWorkManager.a (OSNotificationRestoreWorkManager.java:27)
com.onesignal.OneSignal.onAppFocusLogic (OneSignal.java:29)
com.onesignal.OneSignal.onAppFocus (OneSignal.java:78)
com.onesignal.ActivityLifecycleHandler.d (ActivityLifecycleHandler.java:75)
com.onesignal.ActivityLifecycleHandler.d (ActivityLifecycleHandler.java:28)
com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java:4)
android.app.Application.dispatchActivityResumed (Application.java:438)
```

same issue

**Comment by rishav130** [comment] 2022-02-10 09:12
@jkasten2 why don't you do something about it instead of waiting for it to get fixed by itself with some magic. we all are facing this problem from a long time now, this is shameful one signal

**Comment by bwrelawan** [comment] 2022-02-17 05:00
better using 3.0.0 Version. Its okay to open notification on Xiaomi device but sometimes cant open. But better than nothing XD

**Comment by nileshsoni97** [comment] 2022-02-18 08:39
This Problem is solved. This issue is not from onesignal side just a MIUI issue (Redmi & Mi Mobiles).
Solve this problem by enabling this option in setting of your app.

![photofunny net_](https://user-images.githubusercontent.com/24243815/154647302-7c8c74c3-bf90-499c-8830-a9744ce58632.jpg)

![photofunny net_ (1)](https://user-images.githubusercontent.com/24243815/154647240-02f9bc4f-9f82-46f3-8ca8-7a978f488c47.jpg)

**Comment by tamirrab** [comment] 2022-02-18 08:43
> This Problem is solved. This issue is not from onesignal side just a MIUI issue (Redmi & Mi Mobiles). Solve this problem by enabling this option in setting of your app.
> 
> ![photofunny net_](https://user-images.githubusercontent.com/24243815/154647302-7c8c74c3-bf90-499c-8830-a9744ce58632.jpg)
> 
> ![photofunny net_ (1)](https://user-images.githubusercontent.com/24243815/154647240-02f9bc4f-9f82-46f3-8ca8-7a978f488c47.jpg)

Sorry but I’m not sure you are right 
The previous version is working without it

Also, I can't ask the user to do this

**Comment by rishav130** [comment] 2022-02-18 08:46
> This Problem is solved. This issue is not from onesignal side just a MIUI issue (Redmi & Mi Mobiles). Solve this problem by enabling this option in setting of your app.
> 
> ![photofunny net_](https://user-images.githubusercontent.com/24243815/154647302-7c8c74c3-bf90-499c-8830-a9744ce58632.jpg)
> 
> ![photofunny net_ (1)](https://user-images.githubusercontent.com/24243815/154647240-02f9bc4f-9f82-46f3-8ca8-7a978f488c47.jpg)

Is there a workaround available? Or any other suggestion? As we can't ask the user to do all these steps, no one's gonna do that but just uninstall our app.

**Comment by nileshsoni97** [comment] 2022-02-19 22:30
> > > This Problem is solved. This issue is not from onesignal side just a MIUI issue (Redmi & Mi Mobiles). Solve this problem by enabling this option in setting of your app.
> > 
> > 
> > Sorry but I’m not sure you are right The previous version is working without it
> > Also, I can't ask the user to do this
> 
> Yeap absolutely. This is Onesignal problem. Previous versions working fine but 3.* versions has bugged.

https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/488#issuecomment-1046113965

**Comment by GeceGibi** [comment] 2022-02-20 15:43
it's not the solution btw and issue is not notification dialog show problem. it's when app closed in background and touched to notification dialog app not coming foreground. App not starting with notification touch.

**Comment by murilots** [comment] 2022-03-02 21:50
Same issue with MI 8.

This issue not happen with flutter_local_notifications

**Comment by supermnemonic** [comment] 2022-03-21 08:46
still issue

**Comment by jkasten2** [comment] 2022-04-24 23:15
## Update
### Huawei - With HMS push
The Huawei notification open not foregrounding the app issue will be part of the next release this week.
   - Only a factor on Huawei devices, and if it was sent a HMS message type (default, data type works corretly) notification.
   - The fix was part of the [OneSignal-Android-SDK 4.7.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.0) release which will be included in the update.

### Xiaomi
Notification open not foregrounding the app is an issue for FCM pushes is still ongoing. See https://github.com/OneSignal/OneSignal-Android-SDK/issues/1494 for the latest details.

### Others
There are no known issues with other devices or push types.

CC @Aksoyhlc

**Comment by Samuelbrandani** [comment] 2022-05-04 12:17
same here

**Comment by nan-li** [comment] 2022-05-26 19:20
Hi all,

(1) For the Xiaomi issue, thank you for waiting and the fix is now in the latest `OneSignal-Flutter-SDK` release, [version 3.3.1](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.3.1).

(2) For the issue about `WorkManager is not initialized properly`, it is being tracked at https://github.com/OneSignal/OneSignal-Android-SDK/issues/1561 and investigated. Please see [this comment](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1561#issuecomment-1112705288) if you have more details to share.

**Closed** 2022-05-26 19:32 UTC

**Comment by benjaminhorner** [comment] 2023-11-16 10:36
I am still facing the issue with version 5.0.3…
