### ISSUE TITLE
Notifications not working when application terminate

### ISSUE THREAD

**Issue by krishnapandya** [OneSignal/OneSignal-Flutter-SDK#592] opened 2022-08-25 09:45 UTC
Hello,

I am using onesignal_flutter: ^3.4.1 .

When App is open or in background notification working .but when app terminated not receiving any notification.

**Comment by emawby** [comment] 2022-08-25 17:44
Closing this as a duplicate of #587

**Closed by emawby** 2022-08-25 17:44 UTC
Labels: Duplicate

**Comment by krishnapandya** [comment] 2022-09-12 07:28
Whats the solution??
