### ISSUE TITLE
The plugin `onesignal_flutter` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by nimr77** [OneSignal/OneSignal-Flutter-SDK#487] opened 2021-09-14 21:31 UTC
While using flutter 2.5 I'm getting this warning on building my app

The plugin `onesignal_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it
since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

flutter doctor
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.4 20F71 darwin-x64, locale en-MA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.0)
[✓] Connected device (3 available)

and once I Tap on the notification It doesn't open the app but it opens the handlers, this issue is only on android, as for the IOS it is working perfectly.

**Comment by jesselpereira** [comment] 2021-09-15 13:17
Duplicate of #480

**Comment by emawby** [comment] 2021-09-16 16:27
Closing as duplicate of #480

**Closed by emawby** 2021-09-16 16:27 UTC
