### ISSUE TITLE
OneSignal.h file not found 

### ISSUE THREAD

**Issue by Denmal1982** [OneSignal/OneSignal-Flutter-SDK#33] opened 2018-11-12 06:29 UTC
flutter build ios:

=== BUILD TARGET path_provider OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/myUser/AndroidStudioProjects/myApp/ios/OneSignalNotificationServiceExtension/NotificationService.m:1:9: fatal error: 'OneSignal/OneSignal.h' file not found
#import <OneSignal/OneSignal.h>

flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.13.6 17G65, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

please tell me where is the problem

**Comment by vmihalachi** [comment] 2018-11-12 08:11
I think that's a duplicate of #21 
You should remove `use_frameworks!` from ios/Podfile

**Comment by Denmal1982** [comment] 2018-11-12 10:07
> Я думаю, что это дубликат [# 21](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/21)
> Вы должны удалить `use_frameworks!`из ios / Podfile

And where exactly is this done? I have this code at the end

```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

**Comment by vmihalachi** [comment] 2018-11-12 10:19
every line containing `use_frameworks!` should be commented out with a #.
So your file will most likely end like that

```
target 'OneSignalNotificationServiceExtension' do
  # use_frameworks!
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

Be careful that `use_frameworks!` may be written also upper in the file

**Comment by Denmal1982** [comment] 2018-11-12 16:43
> use_frameworks

then I get it!

`CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-OneSignalNotificationServiceExtension`: (``)

    Finding Podfile changes
      - Flutter
      - OneSignal
      - audio_recorder
      - flutter_app_badger
      - flutter_sound
      - fluttertoast
      - geocoder
      - image_picker
      - map_view
      - onesignal
      - path_provider
      - shared_preferences
      - url_launcher

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `audio_recorder` from `.symlinks/plugins/audio_recorder/ios`
    -> Fetching podspec for `flutter_app_badger` from `.symlinks/plugins/flutter_app_badger/ios`
    -> Fetching podspec for `flutter_sound` from `.symlinks/plugins/flutter_sound/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `geocoder` from `.symlinks/plugins/geocoder/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `map_view` from `.symlinks/plugins/map_view/ios`
    -> Fetching podspec for `onesignal` from `.symlinks/plugins/onesignal/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
    [!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):

    - Runner (true) and OneSignalNotificationServiceExtension (false) do not both set use_frameworks!.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/analyzer.rb:384:in `analyze_host_targets_in_podfile'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/analyzer.rb:415:in `generate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/analyzer.rb:112:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:266:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:136:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'`

**Comment by vmihalachi** [comment] 2018-11-12 16:58
You probably have another line with use frameworks. Write here your Podfile

**Comment by Denmal1982** [comment] 2018-11-12 17:20
Did everything again, with the initial settings, commented as you said

`Launching lib/main.dart on iPhone 5s in debug mode...
Running pod install...
Starting Xcode build...
Xcode build done.                                            2,9s
Failed to build iOS app
Error output from Xcode build:

    ** BUILD FAILED **


Xcode's output:

    <built-in>:1:10: warning: non-portable path to file '"/Users/MyUser/AndroidStudioProjects/MyApp/ios/Pods/Target Support Files/OneSignal/onesignal-prefix.pch"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
    #include "/Users/MyUser/AndroidStudioProjects/MyApp/ios/Pods/Target Support Files/onesignal/onesignal-prefix.pch"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "/Users/MyUser/AndroidStudioProjects/MyApp/ios/Pods/Target Support Files/OneSignal/onesignal-prefix.pch"
    In file included from /Users/MyUser/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.0.3/ios/Classes/OneSignalCategories.m:28:
    /Users/MyUser/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.0.3/ios/Classes/OneSignalCategories.h:28:9: fatal error: 'OneSignal/OneSignal.h' file not found
    #import <OneSignal/OneSignal.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 warning and 1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone 5s.`


My Podfile:

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  #use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end`

**Comment by vmihalachi** [comment] 2018-11-13 08:58
Can't help, sorry, maybe the maintainers of the project can help

**Comment by Nightsd01** [comment] 2018-11-14 18:54
@Denmal1982 can you post your pubspec.yaml...? What version of our Flutter SDK are you using?

**Comment by Nightsd01** [comment] 2018-11-16 21:52
Closing issue due to no response. Please reply if you’re still having this issue (and answer my previous post) and I’ll be happy to reopen.

**Closed by Nightsd01** 2018-11-16 21:52 UTC

**Comment by rogeliotrejo13** [comment] 2019-04-17 22:32
Same issue,

Xcode's output:
↳
    <built-in>:1:10: warning: non-portable path to file '"/Users/roger/flutter/FlutterGoogleMaps/ios/Pods/Target Support
    Files/OneSignal/onesignal-prefix.pch"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
    #include "/Users/roger/flutter/FlutterGoogleMaps/ios/Pods/Target Support Files/onesignal/onesignal-prefix.pch"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "/Users/roger/flutter/FlutterGoogleMaps/ios/Pods/Target Support Files/OneSignal/onesignal-prefix.pch"
    In file included from
    /Users/roger/development/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.1.0/ios/Classes/OneSignalCategories.m:28:
    /Users/roger/development/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.1.0/ios/Classes/OneSignalCategories.h:28:9: fatal error:
    'OneSignal/OneSignal.h' file not found
    #import <OneSignal/OneSignal.h>


-  onesignal: ^1.1.0
I followed all steps from one signal  flutter  documentation. I removed use_frameworks etc

**Comment by tadeucosta00** [comment] 2022-02-17 16:25
onesignal h file not found ios flutter you know why this error?
