### ISSUE TITLE
Clear Push Notifications

### ISSUE THREAD

**Issue by emrahcapar** [OneSignal/OneSignal-Flutter-SDK#219] opened 2020-03-11 08:13 UTC
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by hcaz** [comment] 2020-03-15 20:56
Looks like a duplicate of #184

**Comment by jkasten2** [comment] 2020-03-19 20:01
Closing as a duplicate

**Closed by jkasten2** 2020-03-19 20:01 UTC
