### ISSUE TITLE
fatal error: 'OneSignal/OneSignal.h' file not found

### ISSUE THREAD

**Issue by vikashfleapo2019** [OneSignal/OneSignal-Flutter-SDK#85] opened 2019-05-04 19:55 UTC
i am getting this error  "fatal error: 'OneSignal/OneSignal.h' file not found" when using the onesignal with  flutter. I am using use_frameworks! in my pod file because i need it to support other pods files, help me to solve this error.

**Comment by rgomezp** [comment] 2019-05-06 20:48
Hello,
This is a duplicate of #21 . Please follow it there. Thank you!

**Closed by rgomezp** 2019-05-06 20:48 UTC
