### ISSUE TITLE
Android unsupported value

### ISSUE THREAD

**Issue by mo-ah-dawood** [OneSignal/OneSignal-Flutter-SDK#377] opened 2021-04-07 21:29 UTC
I think there is an error in additionalData parsing

i Got this error when i received any message

`​Unsupported value: {}`

when i tried to send additionalData this message changed 
`Unsupported value: {"dd":"dd"}`

```dart

D/AndroidRuntime(29229): Shutting down VM
E/AndroidRuntime(29229): FATAL EXCEPTION: main
E/AndroidRuntime(29229): Process: com.saned.bargain, PID: 29229
E/AndroidRuntime(29229): java.lang.IllegalArgumentException: Unsupported value: {"dd":"dd"}
E/AndroidRuntime(29229): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:276)
E/AndroidRuntime(29229): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:273)
E/AndroidRuntime(29229): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/AndroidRuntime(29229): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:99)
E/AndroidRuntime(29229): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:83)
E/AndroidRuntime(29229): 	at com.onesignal.flutter.FlutterRegistrarResponder$4.run(FlutterRegistrarResponder.java:73)
E/AndroidRuntime(29229): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(29229): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(29229): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(29229): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(29229): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29229): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(29229): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

> version : ^3.0.0-beta1
> platform: android
> device: real device and emulator

**Comment by hiens** [comment] 2021-04-08 10:22
Same issue

**Comment by codesxt** [comment] 2021-04-19 17:55
I'm using onesignal_flutter: 3.0.0-beta2 by the way.

**Comment by dgilperez** [comment] 2021-04-20 15:05
same issue here - any ETA for v3 to be out?

**Comment by JideGuru** [comment] 2021-04-20 19:47
same issue

**Comment by Jeasmine** [comment] 2021-04-21 00:03
Hey! Yes, we addressed this issue under https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/384 . Thanks all for your feedback!

**Comment by Holofox** [comment] 2021-06-25 10:12
@Jeasmine, as relevant as ever.  This time, the problem is related to clicking on the grouped notifications. 

```console
E/AndroidRuntime( 6283): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.*****.**.**/com.onesignal.NotificationOpenedReceiver}: java.lang.IllegalArgumentException: Unsupported value: [{"androidNotificationId":0,"groupedNotifications":[],"notificationId":"d03ecab7-62a4-4447-9583-f7a395de85a0","templateName":"","templateId":"","title":"@c2j3rj3q3g5msncpgij0","body":"Hello, it‘me","lockScreenVisibility":1,"groupKey":"3fcc781a-c33a-4d86-b173-72b5a2c1b902","groupMessage":"$[notif_count] new messages","fromProjectNumber":"979397403189","priority":0,"additionalData":{"streamID":"3fcc781a-c33a-4d86-b173-72b5a2c1b902"},"rawPayload":"{\"google.delivered_priority\":\"normal\",\"google.sent_time\":1624615389307,\"google.ttl\":259200,\"google.original_priority\":\"normal\",\"custom\":\"{\\\"a\\\":{\\\"streamID\\\":\\\"3fcc781a-c33a-4d86-b173-72b5a2c1b902\\\"},\\\"i\\\":\\\"d03ecab7-62a4-4447-9583-f7a395de85a0\\\"}\",\"grp\":\"3fcc781a-c33a-4d86-b173-72b5a2c1b902\",\"from\":\"979397403189\",\"alert\":\"Hello, it‘s me\",\"title\":\"@c2j3rj3q3g5msncpgij0\",\"grp_msg\":\"$[notif_count] new messages\",\"google.message_id\":\"0:1624615389339656%33115583f9fd7ecd\",\"google.c.sender.id\":\"979397403189\"}"},{"androidNotificationId":0,"groupedNotifications":[],"notificationId":"12fe9e03-b37c-440b-b09b-300546033831","templateName":"","templateId":"","title":"@c2j3rj3q3g5msncpgij0","body":"Just message","lockScreenVisibility":1,"groupKey":"3fcc781a-c33a-4d86-b173-72b5a2c1b902","groupMessage":"$[notif_count] new messages","fromProjectNumber":"979397403189","priority":0,"additionalData":{"streamID":"3fcc781a-c33a-4d86-b173-72b5a2c1b902"},"rawPayload":"{\"google.delivered_priority\":\"normal\",\"google.sent_time\":1624615407051,\"google.ttl\":259200,\"google.original_priority\":\"normal\",\"custom\":\"{\\\"a\\\":{\\\"streamID\\\":\\\"3fcc781a-c33a-4d86-b173-72b5a2c1b902\\\"},\\\"i\\\":\\\"12fe9e03-b37c-440b-b09b-300546033831\\\"}\",\"grp\":\"3fcc781a-c33a-4d86-b173-72b5a2c1b902\",\"from\":\"979397403189\",\"alert\":\"Just message\",\"title\":\"@c2j3rj3q3g5msncpgij0\",\"grp_msg\":\"$[notif_count] new messages\",\"google.message_id\":\"0:1624615407066280%33115583f9fd7ecd\",\"google.c.sender.id\":\"979397403189\"}"},{"androidNotificationId":0,"groupedNotifications":[],"notificationId":"ef12750d-96fb-4613-a814-b2896a3c3fcf","templateName":"","templateId":"","title":"@c2j3rj3q3g5msncpgij0","body":"And this message","lockScreenVisibility":1,"groupKey":"3fcc781a-c33a-4d86-b173-72b5a2c1b902","groupMessage":"$[notif_count] new messages","fromProjectNumber":"979397403189","priority":0,"additionalData":{"streamID":"3fcc781a-c33a-4d86-b173-72b5a2c1b902"},"rawPayload":"{\"google.delivered_priority\":\"normal\",\"google.sent_time\":1624615426106,\"google.ttl\":259200,\"google.original_priority\":\"normal\",\"custom\":\"{\\\"a\\\":{\\\"streamID\\\":\\\"3fcc781a-c33a-4d86-b173-72b5a2c1b902\\\"},\\\"i\\\":\\\"ef12750d-96fb-4613-a814-b2896a3c3fcf\\\"}\",\"grp\":\"3fcc781a-c33a-4d86-b173-72b5a2c1b902\",\"from\":\"979397403189\",\"alert\":\"And this message\",\"title\":\"@c2j3rj3q3g5msncpgij0\",\"grp_msg\":\"$[notif_count] new messages\",\"google.message_id\":\"0:1624615426133886%33115583f9fd7ecd\",\"google.c.sender.id\":\"979397403189\"}"}]
E/AndroidRuntime( 6283): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/AndroidRuntime( 6283): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime( 6283): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime( 6283): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6283): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6283): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 6283): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6283): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6283): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 6283): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6283): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6283): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

```
onesignal_flutter 3.0.0
```

```
Flutter 2.2.2 • channel unknown • unknown source
Framework • revision d79295af24 (2 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

#357

**Comment by dgilperez** [comment] 2021-06-25 12:49
We are seeing the exact same error as @Holofox, @Jeasmine. We're not sure how visible / breaking it is for our users. I was not able to diagnose the problem. Holofox, could you please elaborate on ` clicking on the grouped notifications`? Is there something we can modify in the notifications we send to avoid this error? Thanks a lot.

**Comment by Holofox** [comment] 2021-06-29 14:07
@dgilperez, I opened #423 pull request.

**Comment by dgilperez** [comment] 2021-06-29 15:34
Nice @Holofox! Change seems obvious / straightforward, but I lack the knowledge on the internals. 

Did you try it live? Does it work for you?

**Comment by Holofox** [comment] 2021-06-29 16:24
@dgilperez, this can be reproduced by sending multiple push notifications to get them into a group. Our case covers a chat between two interlocutors, when several messages can come from one user.

For us, the problem was solved, the application no longer crashes and, judging by the logs, the rest of the logic is being worked out, but another problem has appeared, which is that it is impossible to track the click on such notifications (the click event is not called).

**Comment by jkasten2** [comment] 2022-02-16 06:40
Closing as the PR above as solved the issue based on the reports above.

**Closed by jkasten2** 2022-02-16 06:40 UTC
