### ISSUE TITLE
getting this error when try to use one signal sdk flutter

### ISSUE THREAD

**Issue by vikashfleapo2019** [OneSignal/OneSignal-Flutter-SDK#86] opened 2019-05-06 08:10 UTC
Xcode build done.                                            8.5s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-05-06 13:36:31.562 xcodebuild[88988:711836] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application
    Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    ** BUILD FAILED **

Xcode's output:
↳
    <built-in>:1:10: warning: non-portable path to file '"/Users/user/DevelopmentFlutter/VendoreKS/ios/Pods/Target Support Files/OneSignal/onesignal-prefix.pch"'; specified path differs in case from file name on disk
    [-Wnonportable-include-path]
    #include "/Users/user/DevelopmentFlutter/VendoreKS/ios/Pods/Target Support Files/onesignal/onesignal-prefix.pch"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "/Users/user/DevelopmentFlutter/VendoreKS/ios/Pods/Target Support Files/OneSignal/onesignal-prefix.pch"
    In file included from /Users/user/DevelopmentFlutter/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.1.0/ios/Classes/OneSignalCategories.m:28:
    /Users/user/DevelopmentFlutter/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.1.0/ios/Classes/OneSignalCategories.h:28:9: fatal error: 'OneSignal/OneSignal.h' file not found
    #import <OneSignal/OneSignal.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 warning and 1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by rgomezp** [comment] 2019-05-06 20:49
Hello,
This is also a duplicate of #21 . Please follow it there! Thanks.

**Closed by rgomezp** 2019-05-06 20:49 UTC
