### ISSUE TITLE
OneSignal.h not  fount

### ISSUE THREAD

**Issue by htetwaiyan** [OneSignal/OneSignal-Flutter-SDK#76] opened 2019-04-05 08:51 UTC
In file included from /Users/htetwaiyan/htetwaiyan/flutter_dev/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.1.0/ios/Classes/OneSignalCategories.m:28:
    /Users/htetwaiyan/htetwaiyan/flutter_dev/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.1.0/ios/Classes/OneSignalCategories.h:28:9: fatal error: 'OneSignal/OneSignal.h' file not found
    #import <OneSignal/OneSignal.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by rgomezp** [comment] 2019-04-08 18:32
Duplicate of #21

**Closed by rgomezp** 2019-04-08 18:32 UTC
