### ISSUE TITLE
Notification icon won't get change to my app icon

### ISSUE THREAD

**Issue by heshaShawky** [OneSignal/OneSignal-Flutter-SDK#257] opened 2020-06-15 00:39 UTC
**Description:**

The notification icon for android won't set! I followed the android documentation for setting an icon but didn't work for me, I have generated an assets Image using the Android studio at `android/app/src/main/res` with the name `ic_stat_onesignal_default` but nothing still all my notification comes with the default bill icon! 

<a href="https://ibb.co/Yj05H5m"><img src="https://i.ibb.co/Yj05H5m/Screen-Shot-2020-06-15-at-2-37-04-AM.png" alt="Screen-Shot-2020-06-15-at-2-37-04-AM" border="0"></a>

**Environment**

1. OneSignal Flutter SDK Version: ^2.4.1
2. Flutter doctor -v
```bash
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.14.5 18F132, locale en-EG)
    • Flutter version 1.17.2 at /Users/esham/Development/flutter
    • Framework revision 5f21edf8b6 (2 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/esham/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/esham/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/esham/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Redmi Note 8 Pro • hev4t4bqo7hyvsnf • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
``` 

**Steps to Reproduce Issue:**

1. I have generated an assets image with name `ic_stat_onesignal_default`

**Anything else:**

I guess there a code should put on the manifest file but didn't find what is it?

**Comment by rgomezp** [comment] 2020-06-16 00:45
Duplicate of #249

**Closed by rgomezp** 2020-06-16 00:45 UTC
