### ISSUE TITLE
Unsupported value: null on OneSignalRestClient.java:208

### ISSUE THREAD

**Issue by putraxor** [OneSignal/OneSignal-Flutter-SDK#23] opened 2018-09-23 23:51 UTC
Occurs when sending notification
```java
    var imgUrlString = "https://zonaskripsi.com/img/algorithm-simulator.jpg";

    var notification = OSCreateNotification(
      playerIds: [playerId],
      content: "this is a test from OneSignal's Flutter SDK",
      heading: "Hi There",
      bigPicture: imgUrlString,
      androidSound: 'default',
      androidSmallIcon: 'ic_stat_notif',
      androidLargeIcon:
          'https://lh3.googleusercontent.com/-2CP3JmsQzco/AAAAAAAAAAI/AAAAAAAAAAA/AAN31DXIEj2LOgTMtJlA-88kDMjwmxMSEw/s64-c-mo/photo.jpg',
      additionalData: {
        'foo': 'this is a foo value',
        'bar': 'this is a bar value'
      },
    );

    var response = await signal.postNotification(notification);
```
Error logs
```java
W/System.err( 3167): java.lang.IllegalArgumentException: Unsupported value: null
W/System.err( 3167): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
W/System.err( 3167): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:290)
W/System.err( 3167): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
W/System.err( 3167): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
W/System.err( 3167): 	at com.onesignal.flutter.OneSignalPlugin$1.onSuccess(OneSignalPlugin.java:184)
W/System.err( 3167): 	at com.onesignal.OneSignal$12.onSuccess(OneSignal.java:1567)
W/System.err( 3167): 	at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:208)
W/System.err( 3167): 	at java.lang.Thread.run(Thread.java:764)
```
Dependency
```
dependencies:
    onesignal: ^1.0.0
```

**Comment by Nightsd01** [comment] 2018-09-26 23:27
Hi, thanks for reporting this, will investigate and will get back to you as shortly as possible. This is likely a bug with our SDK.

**Comment by Nightsd01** [comment] 2018-09-27 23:42
@putraxor After investigating a bit, I think you must be using an older version of our SDK because we fixed this in the last release.

Can you try changing your pubspec to the following just to make absolutely sure you are using the new version of our SDK and not an old version?

```yaml
dependencies:
    onesignal: ^1.0.2
```

**Comment by Nightsd01** [comment] 2018-09-28 18:30
@putraxor Just out of curiosity, why are you using `signal` instead of our singleton `OneSignal.shared`?

**Comment by Nightsd01** [comment] 2018-09-28 23:06
We've discovered the root cause of this issue and have created a [fix here](https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/26) - it will be included in a new release next week.

The issue was due to a strange quirk with how Android's `JSONObject` handles null - in fact it uses its own special type of `JSONObject.NULL` and a simple equality check against Java's `null` will return false!

Thank you for posting this issue

**Closed by Nightsd01** 2018-09-28 23:06 UTC
