### ISSUE TITLE
App crashes on Android at first launch

### ISSUE THREAD

**Issue by Mapk26** [OneSignal/OneSignal-Flutter-SDK#162] opened 2019-10-23 14:29 UTC
**Description:**
App crashes at first launch. 
It works fine up to Oct. 9 (last app release on the Play Store), no changes at the code, only flutter update.

**Environment**
Version: OneSignal 2.1.0

build.gradle:
```gradle
buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.5, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'`
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale it-IT)
    • Flutter version 1.9.1+hotfix.4 at /Users/mnicotra/dev/flutter
    • Framework revision cc949a8e8b (4 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mnicotra/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • SM G955F • ce021712099adb3102 • android-arm64 • Android 9 (API 28)`
```

**Steps to Reproduce Issue:**

1. Install OneSignal Flutter SDK
2. Init OneSignal as always done so far.
3. Build and install 
4. Launch the app (very first time), it will crash after few secs.

**Anything else:**

```java
Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.FirebaseMessagingService>: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.xxx.pixxxo-tgNjf2Q_Cz6sbXDxJ6enUQ==/base.apk)
I/xxx(26229):   at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/xxx(26229):   at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:738)
I/xxx(26229):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:363)
I/xxx(26229):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/xxx(26229):   at android.app.Service android.app.AppComponentFactory.instantiateService(java.lang.ClassLoader, java.lang.String, android.content.Intent) (AppComponentFactory.java:103)
I/xxx(26229):   at android.app.Service androidx.core.app.CoreComponentFactory.instantiateService(java.lang.ClassLoader, java.lang.String, android.content.Intent) (CoreComponentFactory.java:68)
I/xxx(26229):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3738)
I/xxx(26229):   at void android.app.ActivityThread.access$1400(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:237)
I/xxx(26229):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1801)
I/xxx(26229):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/xxx(26229):   at void android.os.Looper.loop() (Looper.java:214)
I/xxx(26229):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7050)
I/xxx(26229):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/xxx(26229):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/xxx(26229):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:965)
I/xxx(26229):
D/AndroidRuntime(26229): Shutting down VM
E/AndroidRuntime(26229): FATAL EXCEPTION: main
E/AndroidRuntime(26229): Process: com.xxx.pixxxo, PID: 26229
E/AndroidRuntime(26229): java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.xxx.pixxxo-tgNjf2Q_Cz6sbXDxJ6enUQ==/base.apk)
E/AndroidRuntime(26229): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime(26229): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime(26229): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime(26229): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(26229): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
E/AndroidRuntime(26229): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
E/AndroidRuntime(26229): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3738)
E/AndroidRuntime(26229): 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
E/AndroidRuntime(26229): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
E/AndroidRuntime(26229): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26229): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(26229): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/AndroidRuntime(26229): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26229): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(26229): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`
```

**Comment by royrakesh** [comment] 2019-10-24 04:55
Same issue its working fine, but after a clean build its crashing on launch from tomorrow.

**Comment by Mapk26** [comment] 2019-10-24 08:08
@royrakesh try this (for me seems to solve the issue)

in your dependencies add firebase dependency like below:

`dependencies {
    ...
    implementation 'com.onesignal:OneSignal:[3.11.2, 3.99.99]'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
}`

run flutter clean + flutter packages get.
Then build and run.
It didn't crash in my case, I also tried to remove the implementation of Firebase Messaging and build again. Crash!

Please let me know if it works and if you find any issue with this workaround.

**Comment by Mapk26** [comment] 2019-10-24 09:41
`environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  http: ^0.12.0+2
  rxdart: ^0.19.0
  package_info: ^0.4.0+6
  cached_network_image: ^1.1.1
  url_launcher: ^5.1.2
  fluttertoast: ^3.1.0
  flutter_html: ^0.10.4
  flutter_spinkit: ^3.1.0
  share: ^0.6.2+1
  sqflite: ^1.1.5
  device_info: ^0.4.0+2
  sticky_headers: ^0.1.8
  flutter_secure_storage: ^3.2.1+1
  provider: ^3.0.0+1
  flutter_facebook_login: ^3.0.0
  onesignal_flutter: ^2.1.0
  introduction_screen: ^1.0.6
  notification_permissions: ^0.4.0
  device_id: ^0.2.0
  liquid_pull_to_refresh: ^1.1.1
  webview_flutter: ^0.3.13
  uni_links: ^0.2.0
  badges: ^1.1.0
  firebase_analytics: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter`

**Comment by royrakesh** [comment] 2019-10-24 10:12
Thanks @Mapk26  it works. 
I am using  `firebase_admob: ^0.9.0+7 ,   onesignal_flutter: ^2.1.0` which causing the issue.

**Comment by Mapk26** [comment] 2019-10-24 13:08
> Thanks @Mapk26 your sol^ works when i run debug build but diffrent error on release build.
> I am using `firebase_admob: ^0.9.0+7 , onesignal_flutter: ^2.1.0` which causing the issue.
> 
> **

It's working fine in release mode for me, 
does it build and then give an error on launching the app?

You could try downgrading your admob to 0.9.0+6.

By the way, we should wait for someone from the OneSignal team to look into this issue (similar to #116 ) and maybe release a fix.

**Comment by royrakesh** [comment] 2019-10-25 09:34
> > Thanks @Mapk26 your sol^ works when i run debug build but diffrent error on release build.
> > I am using `firebase_admob: ^0.9.0+7 , onesignal_flutter: ^2.1.0` which causing the issue.
> > **
> 
> It's working fine in release mode for me,
> does it build and then give an error on launching the app?
> 
> You could try downgrading your admob to 0.9.0+6.
> 
> By the way, we should wait for someone from the OneSignal team to look into this issue (similar to #116 ) and maybe release a fix.

After lots of trail able to fix the issue with just by commenting one line
@Mapk26  Thanks again 


![image](https://user-images.githubusercontent.com/15174104/67560516-ac275980-f738-11e9-9295-9a393b1ab7a7.png)

**Comment by jkasten2** [comment] 2019-10-25 19:18
@Mapk26 The error looks to be an issue with mismatched versions of Firebase inter dependencies. Can you confirm you have followed the [Add the OneSignal Gradle Plugin](https://documentation.onesignal.com/docs/flutter-sdk-setup#section-4-add-the-onesignal-gradle-plugin-android-) guide? Let us know if this allows you to enable `minifyEnabled` again.

**Comment by royrakesh** [comment] 2019-10-26 05:52
> @Mapk26 The error looks to be an issue with mismatched versions of Firebase inter dependencies. Can you double check that you have `apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'` on line 1 of your `android/app/build.gradle` file? See [Add the OneSignal Gradle Plugin](https://documentation.onesignal.com/docs/flutter-sdk-setup#section-4-add-the-onesignal-gradle-plugin-android-) guide to double check this. Let us know if this allows you to enable `minifyEnabled` again.

I checked with a fresh project with onesignal sdk [with [instruction ](https://documentation.onesignal.com/docs/flutter-sdk-setup#section-4-add-the-onesignal-gradle-plugin-android-)] and it works, but whenever tried with `firebase_admob ` the build failed vise versa. 

Though workaround provided by @Mapk26 works perfectly but i have to disable minify for release build.

**Comment by Mapk26** [comment] 2019-10-28 13:04
> @Mapk26 The error looks to be an issue with mismatched versions of Firebase inter dependencies. Can you double check that you have `apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'` on line 1 of your `android/app/build.gradle` file? See [Add the OneSignal Gradle Plugin](https://documentation.onesignal.com/docs/flutter-sdk-setup#section-4-add-the-onesignal-gradle-plugin-android-) guide to double check this. Let us know if this allows you to enable `minifyEnabled` again.

Hello @jkasten2 , yes I confirm that the app/build.gradle is exactly how explained in the Flutter SDK Setup doc.
If I don't add the firebase messaging (com.google.firebase:firebase-messaging:20.0.0) the app crashes at the first launch.

In my case I'm using 'firebase_analytics: ^5.0.1' in the pubspec.

I would also point out that everything worked perfectly before October 5th (date of my latest published release). The only thing changed recently was by "flutter upgrade".

Thank you

**Comment by rgomezp** [comment] 2019-11-07 21:58
Duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/754

Please follow the other thread

**Closed by rgomezp** 2019-11-07 21:58 UTC

**Comment by arutkayb** [comment] 2020-04-22 06:22
Followed the guideline :
https://github.com/OneSignal/OneSignal-Gradle-Plugin
instead of
https://documentation.onesignal.com/docs/flutter-sdk-setup because the gradle levels are wrong

Also added
implementation 'com.google.firebase:firebase-messaging:18.0.0'
implementation 'com.google.firebase:firebase-iid:18.0.0'
into app level gradle and solved
