### ISSUE TITLE
Flutter Android: tapping push notification opens second .MainActivity duplicating flutter app

### ISSUE THREAD

**Issue by lukepighetti** [OneSignal/OneSignal-Flutter-SDK#411] opened 2021-06-09 20:14 UTC
**Description:**

We're running into a situation where tapping on a push notification on Android launches a new `.MainActivity` activity which duplicates the Flutter app and starts it fresh with a loading screen. The original/underlying activity receives the push notification payload and is not visible because it's covered by the new activity. You can press the Android back button to pop the new app and show the underlying original app which has successfully received the push notification payload.

**Environment**

^3.0.0-beta4
pub

```
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (13 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

**Steps to Reproduce Issue:**

1. tap push notification
2. .MainActivity activity duplicates

**Comment by lailai0715** [comment] 2021-06-16 04:07
I think I faced the same issue with you, any solution yet?

**Comment by lukepighetti** [comment] 2021-06-17 12:12
Had to switch to `launchMode=singleTask` in `AndroidManifest.xml`

If you find another way please let me know

**Comment by emawby** [comment] 2021-07-29 19:06
closing as a duplicate of #407

**Closed by emawby** 2021-07-29 19:06 UTC
