### ISSUE TITLE
Error updating the user record because of the null user id

### ISSUE THREAD

**Issue by enricobenedos** [OneSignal/OneSignal-Flutter-SDK#247] opened 2020-05-21 15:28 UTC
**Description:**

I'm not able to subscribe to notifications with my Android and iOS devices. On iOS there are not printed logs but on Android this is the output:
```log
V/OneSignal(21016): Initializing the OneSignal Flutter SDK (2.2.0)
E/OneSignal(21016): Cannot change requiresUserPrivacyConsent() from TRUE to FALSE
D/EGL_emulation(21016): eglMakeCurrent: 0xdb85dda0: ver 3 0 (tinfo 0xdb7db9d0)
I/flutter (21016): Notifications initialized
I/flutter (21016): No walktrought SVGs preloaded
I/flutter (21016): Now will load always necessary SVGs
E/OneSignal(21016): Error updating the user record because of th enull user id
```

**Environment**

```terminal
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
```

```yaml
onesignal_flutter: ^2.4.1
```
My Android emulator use `API 28` and my real iOS device has `iOS 13.4.1`

**Steps to Reproduce Issue:**

1. Run this code on `main.dart`
```dart
void initState() {
    super.initState();
    _initOneSignalNotifications()
        .then((value) => print('Notifications initialized'));
  }

Future<void> _initOneSignalNotifications() async {
    //Remove this method to stop OneSignal Debugging
    //await OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);

    //Configuring OneSignal SDK
    await OneSignal.shared.init("6cdcda5e-949d-4b4a-ae81-15f0e2a7e125",
        iOSSettings: {
          OSiOSSettings.autoPrompt: false,
          OSiOSSettings.inAppLaunchUrl: false
        });

    await OneSignal.shared.setRequiresUserPrivacyConsent(true);
    await OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);
  }
```
2. UI switch code to enable/disable notifications
```dart
onChanged: (bool value) async {
                    //Check if user has accepted privacy policy about notifications
                    final bool requiredPrivacy =
                        await OneSignal.shared.requiresUserPrivacyConsent();

                    if (requiredPrivacy) {
                      //TODO: improve dialog to include images and privacy policy
                      final result = await GlobalMethods.showChooseDialog(
                          context,
                          'Enable Notifications',
                          'Notifications will help you to know when a new experience is available!');
                      if (result) {
                        await OneSignal.shared
                            .consentGranted(true);
                        if (Platform.isIOS) {
                          await OneSignal.shared
                              .promptUserForPushNotificationPermission(
                                  fallbackToSettings: true);
                        }
                      }
                    }

                    final bool requiredPrivacy2 =
                        await OneSignal.shared.requiresUserPrivacyConsent();
                    if (!requiredPrivacy2) {
                      await OneSignal.shared
                          .setSubscription(!_notificationsEnabled);

                      setState(() {
                        _notificationsEnabled = !_notificationsEnabled;
                      });
                    }
```
**Anything else:**

There is also another problem in the OneSignal output that tell me 
`E/OneSignal(21016): Cannot change requiresUserPrivacyConsent() from TRUE to FALSE`
and I'm already subscribed to this [issue](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/177).
On iOS as tell you first there are not generated console log. And it seems that on iOS when it works, it need a lot of time (1/2hours) to subscribe to notifications (visible on OneSignal website subscribed devices)

Thank you

**Comment by rgomezp** [comment] 2020-06-03 00:34
Duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/1008

**Comment by rgomezp** [comment] 2020-06-03 00:35
Howdy,
Thanks for opening the issue. We are aware of it and are working to fix it as soon as possible. Please follow the thread in the native repository. Thank you

**Closed by rgomezp** 2020-06-03 00:34 UTC
