### ISSUE TITLE
[Bug]: OneSignal Flutter notification open handler (iOS) issue in 5.0.0

### ISSUE THREAD

**Issue by hamzasharif1199** [OneSignal/OneSignal-Flutter-SDK#741] opened 2023-09-15 13:01 UTC
### What happened?

Whereas, in Flutter One signal version 5.0.0 addClickListener is not working and the app is not opening in iOS when it’s killed totally from the background. On your official documentation, there is a video of flutter implementation in both iOS and Android but following that I am getting notifications that when the app is killed it's not working and you need to fix it as soon as possible or maybe you can give a complete detailed video so we can know it better. Somebody also reported 2 weeks before and still open kindly fix all the issues because it's so hard if we use one signal for Android and something else for iOS.

### Steps to reproduce?

```Markdown
1. Implemented everything the same as the official video
2. Install app
3. ios getting notification
4. if the app is not in the background it will not open
```

### What did you expect to happen?

I expect to open the app and perform the specific action.

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment] 2023-09-15 19:52
Closing as a duplicate of #723

**Closed by emawby** 2023-09-15 19:52 UTC
