### ISSUE TITLE
[Bug]: com.amazon.device.iap.internal

### ISSUE THREAD

**Issue by bugrevealingbme** [OneSignal/OneSignal-Flutter-SDK#730] opened 2023-09-05 18:05 UTC
### What happened?

This error comes up when I open the application or change the color mode of the device. Sometimes the app crashes after this error. When the device first starts, the application has stopped error appears.

### Steps to reproduce?

```Markdown
1. Starting the app
```

### What did you expect to happen?

This error comes up when I open the application or change the color mode of the device.

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
Launching lib/main.dart on Redmi K30 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:56561/t0mFkwpspJw=/ws
E/MethodChannel#OneSignal(30747): Failed to handle method call
E/MethodChannel#OneSignal(30747): java.lang.IllegalArgumentException: Expected receiver of type com.amazon.device.iap.internal.d, but got kotlin.Unit
E/MethodChannel#OneSignal(30747): 	at java.lang.reflect.Field.get(Native Method)
E/MethodChannel#OneSignal(30747): 	at com.onesignal.core.internal.purchases.impl.TrackAmazonPurchase.start(TrackAmazonPurchase.kt:83)
E/MethodChannel#OneSignal(30747): 	at com.onesignal.core.internal.startup.StartupService.start(StartupService.kt:16)
E/MethodChannel#OneSignal(30747): 	at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:247)
E/MethodChannel#OneSignal(30747): 	at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
E/MethodChannel#OneSignal(30747): 	at com.onesignal.flutter.OneSignalPlugin.initWithContext(OneSignalPlugin.java:128)
E/MethodChannel#OneSignal(30747): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:111)
E/MethodChannel#OneSignal(30747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#OneSignal(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#OneSignal(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#OneSignal(30747): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#OneSignal(30747): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#OneSignal(30747): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#OneSignal(30747): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#OneSignal(30747): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#OneSignal(30747): 	at android.app.ActivityThread.main(ActivityThread.java:8337)
E/MethodChannel#OneSignal(30747): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#OneSignal(30747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/MethodChannel#OneSignal(30747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
E/DartMessenger(30747): Uncaught exception in binary message listener
E/DartMessenger(30747): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger(30747): 	at com.onesignal.internal.OneSignalImp.getInAppMessages(OneSignalImp.kt:83)
E/DartMessenger(30747): 	at com.onesignal.OneSignal.getInAppMessages(OneSignal.kt:78)
E/DartMessenger(30747): 	at com.onesignal.flutter.OneSignalInAppMessages.lifecycleInit(OneSignalInAppMessages.java:90)
E/DartMessenger(30747): 	at com.onesignal.flutter.OneSignalInAppMessages.onMethodCall(OneSignalInAppMessages.java:52)
E/DartMessenger(30747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(30747): 	at android.os.Handler.handleCallback(Handler.java:938)
E/DartMessenger(30747): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(30747): 	at android.os.Looper.loopOnce(Looper.java:210)
E/DartMessenger(30747): 	at android.os.Looper.loop(Looper.java:299)
E/DartMessenger(30747): 	at android.app.ActivityThread.main(ActivityThread.java:8337)
E/DartMessenger(30747): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(30747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/DartMessenger(30747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
E/DartMessenger(30747): Uncaught exception in binary message listener
E/DartMessenger(30747): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger(30747): 	at com.onesignal.internal.OneSignalImp.getUser(OneSignalImp.kt:84)
E/DartMessenger(30747): 	at com.onesignal.OneSignal.getUser(OneSignal.kt:46)
E/DartMessenger(30747): 	at com.onesignal.flutter.OneSignalPushSubscription.onMethodCall(OneSignalPushSubscription.java:45)
E/DartMessenger(30747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(30747): 	at android.os.Handler.handleCallback(Handler.java:938)
E/DartMessenger(30747): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(30747): 	at android.os.Looper.loopOnce(Looper.java:210)
E/DartMessenger(30747): 	at android.os.Looper.loop(Looper.java:299)
E/DartMessenger(30747): 	at android.app.ActivityThread.main(ActivityThread.java:8337)
E/DartMessenger(30747): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(30747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/DartMessenger(30747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
E/DartMessenger(30747): Uncaught exception in binary message listener
E/DartMessenger(30747): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger(30747): 	at com.onesignal.internal.OneSignalImp.getNotifications(OneSignalImp.kt:81)
E/DartMessenger(30747): 	at com.onesignal.OneSignal.getNotifications(OneSignal.kt:62)
E/DartMessenger(30747): 	at com.onesignal.flutter.OneSignalNotifications.onMethodCall(OneSignalNotifications.java:54)
E/DartMessenger(30747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(30747): 	at android.os.Handler.handleCallback(Handler.java:938)
E/DartMessenger(30747): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(30747): 	at android.os.Looper.loopOnce(Looper.java:210)
E/DartMessenger(30747): 	at android.os.Looper.loop(Looper.java:299)
E/DartMessenger(30747): 	at android.app.ActivityThread.main(ActivityThread.java:8337)
E/DartMessenger(30747): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(30747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/DartMessenger(30747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
E/DartMessenger(30747): Uncaught exception in binary message listener
E/DartMessenger(30747): java.lang.Exception: Must call 'initWithContext' before use
E/DartMessenger(30747): 	at com.onesignal.internal.OneSignalImp.getNotifications(OneSignalImp.kt:81)
E/DartMessenger(30747): 	at com.onesignal.OneSignal.getNotifications(OneSignal.kt:62)
E/DartMessenger(30747): 	at com.onesignal.flutter.OneSignalNotifications.requestPermission(OneSignalNotifications.java:77)
E/DartMessenger(30747): 	at com.onesignal.flutter.OneSignalNotifications.onMethodCall(OneSignalNotifications.java:56)
E/DartMessenger(30747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger(30747): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(30747): 	at android.os.Handler.handleCallback(Handler.java:938)
E/DartMessenger(30747): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(30747): 	at android.os.Looper.loopOnce(Looper.java:210)
E/DartMessenger(30747): 	at android.os.Looper.loop(Looper.java:299)
E/DartMessenger(30747): 	at android.app.ActivityThread.main(ActivityThread.java:8337)
E/DartMessenger(30747): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(30747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/DartMessenger(30747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
I/DpmTcmClient(30747): RegisterTcmMonitor from: $Proxy2
E/flutter (30747): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Expected receiver of type com.amazon.device.iap.internal.d, but got kotlin.Unit, null, java.lang.IllegalArgumentException: Expected receiver of type com.amazon.device.iap.internal.d, but got kotlin.Unit
E/flutter (30747): 	at java.lang.reflect.Field.get(Native Method)
E/flutter (30747): 	at com.onesignal.core.internal.purchases.impl.TrackAmazonPurchase.start(TrackAmazonPurchase.kt:83)
E/flutter (30747): 	at com.onesignal.core.internal.startup.StartupService.start(StartupService.kt:16)
E/flutter (30747): 	at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:247)
E/flutter (30747): 	at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
E/flutter (30747): 	at com.onesignal.flutter.OneSignalPlugin.initWithContext(OneSignalPlugin.java:128)
E/flutter (30747): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:111)
E/flutter (30747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (30747): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (30747): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (30747): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (30747): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (30747): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (30747): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter (30747): 	at android.os.Looper.loop(Looper.java:299)
E/flutter (30747): 	at android.app.ActivityThread.main(ActivityThread.java:8337)
E/flutter (30747): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (30747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter (30747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
E/flutter (30747): )
E/flutter (30747): #0      StandardMethodCodec.decodeEnvelope
E/flutter (30747): #1      MethodChannel._invokeMethod
E/flutter (30747): <asynchronous suspension>
E/flutter (30747):
E/flutter (30747): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#lifecycleInit on channel OneSignal#inappmessages)
E/flutter (30747): #0      MethodChannel._invokeMethod
E/flutter (30747): <asynchronous suspension>
E/flutter (30747): #1      OneSignalInAppMessages.lifecycleInit
E/flutter (30747): <asynchronous suspension>
E/flutter (30747):
E/flutter (30747): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#pushSubscriptionToken on channel OneSignal#pushsubscription)
E/flutter (30747): #0      MethodChannel._invokeMethod
E/flutter (30747): <asynchronous suspension>
E/flutter (30747): #1      OneSignalPushSubscription.lifecycleInit
E/flutter (30747): <asynchronous suspension>
E/flutter (30747):
E/flutter (30747): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#permission on channel OneSignal#notifications)
E/flutter (30747): #0      MethodChannel._invokeMethod
E/flutter (30747): <asynchronous suspension>
E/flutter (30747): #1      OneSignalNotifications.lifecycleInit
E/flutter (30747): <asynchronous suspension>
E/flutter (30747):
E/flutter (30747): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#requestPermission on channel OneSignal#notifications)
E/flutter (30747): #0      MethodChannel._invokeMethod
E/flutter (30747): <asynchronous suspension>
E/flutter (30747): #1      OneSignalNotifications.requestPermission
E/flutter (30747): <asynchronous suspension>
E/flutter (30747):
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcotrumpet** [comment] 2023-09-07 10:32
I have this too, any way to solve? I can only test on Android Emulator. On iOS everything is fine

**Comment by emawby** [comment] 2023-09-15 20:01
closing as duplicate of #709

**Closed by emawby** 2023-09-15 20:01 UTC
Labels: Duplicate
