### ISSUE TITLE
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should u

### ISSUE THREAD

**Issue by daniel-van-niekerk** [OneSignal/OneSignal-Flutter-SDK#68] opened 2019-03-13 12:02 UTC
The sdk complains about this.

`WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead`

I read an issue on the OneSignal IOS sdk github that the sdk needed updating.

My flutter version is 1.2.1 and the onesignal-flutter plugin is  ^1.1.0

**Comment by daniel-van-niekerk** [comment] 2019-03-13 13:31
Sorry I meant 

OneSignal.shared.setPermissionObserver((OSPermissionStateChanges changes) {
         print('Changes'); 
});

does not get called when tapping to allow push notifications in ios.

OneSignal.shared.getPermissionSubscriptionState works.

**Comment by jkasten2** [comment] 2019-03-19 20:41
@daniel-van-niekerk Thanks for the report. These entries are printed from the OneSignal-iOS-SDK that this Flutte SDK uses.
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/aa59b92fb0b9c0a5343bdd5346282212de80976c/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L673-L681

The warning is noting that another part of your app, either your own native code or another plugin is using the `application:didReceiveLocalNotification:` method.

I recommend checking the list of plugins in your project and seeing if you have one for local notifications. If so please open an issue with the that plugin developer to have them upgrade to the `UNUserNotificationCenter`.

**Comment by ltvan** [comment] 2019-11-04 04:58
onesignal-flutter:2.1.0, I got this issue even in new flutter app (flutter create). 

I found this in FlutterPlugin.h (ios/.symlinks/flutter/ios):

```C
/**
 * Calls all plugins registered for `UIApplicationDelegate` callbacks.
 */
- (void)application:(UIApplication*)application
    didReceiveLocalNotification:(UILocalNotification*)notification
    API_DEPRECATED(
        "See -[UIApplicationDelegate application:didReceiveLocalNotification:] deprecation",
        ios(4.0, 10.0));
```

**Comment by om-ha** [comment] 2020-05-07 11:17
Can confirm, perhaps the new stable channel build `1.17.0` would fix this from @ltvan comment?

**Comment by polilluminato** [comment] 2020-07-21 06:38
I've got `onesignal_flutter: ^2.6.0` and flutter `1.17.5` and I see the warning in the debug console on iOS Simulator.

**Comment by valterh4ck3r** [comment] 2020-08-10 17:22
Same issue

**Comment by GusRodrigues86** [comment] 2020-08-18 18:32
2.6.0 and flutter 1.20, same issue, with a new project

**Comment by fooshyangsong** [comment] 2020-09-02 16:56
Same issue, is there's any solution for this?  I had implement UNUserNotificationCenter but still getting this warning. Do I need any configure in Xcode app delegate?

**Comment by mateusfccp** [comment] 2020-09-21 18:53
I am also having this with 2.6.0 and Flutter 1.20.4.

**Comment by KoofNG** [comment] 2020-09-23 14:03
Same issue. Using Flutter v1.20.4 and oneSignal v2.6.1

**Comment by tamirrab** [comment] 2020-10-12 17:22
Same here
Why this issue is close?

**Comment by maxlapides** [comment] 2021-01-06 23:57
@rgomezp Can we please re-open this issue? It is clearly an open problem with no resolution.

**Comment by fluttertests** [comment] 2021-02-27 13:00
> @rgomezp Can we please re-open this issue? It is clearly an open problem with no resolution.

Any update?

**Comment by abbas-25** [comment] 2021-03-27 06:17
Having the same issue, commenting because it seems not being addressed.

**Comment by codiantbiztech** [comment] 2021-03-28 12:53
same problem on flutter 1.22, onesignal 2.6.3
Not able to get rid of it since two days

**Comment by TheChileanKink** [comment] 2021-03-29 00:15
Same warning here!

**Comment by daoibrahim** [comment] 2021-03-30 14:21
Same issue here. Any solution?

**Comment by walvespit** [comment] 2021-03-31 12:16
Same here, any solution ?

**Comment by gilthonweapps** [comment] 2021-04-15 19:06
Hi, any update on that one? The warning is still happening with version 3.0.0-beta2

**Comment by Jeasmine** [comment] 2021-05-15 19:15
Hey all! This is a problem with flutter integration. From OneSignal, we detect this method 
`- (void)application:(UIApplication*)application`
being implemented by https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm.
Even if you guys are not using it until Flutter side removes it, OneSignal will warn it. 
We recommend not to use this method since it will end on making OneSignal not work correctly. We already asked the Flutter community to know when they are going to remove this method of support. Keep track of https://github.com/flutter/flutter/issues/82625.

**Comment by maxlapides** [comment] 2021-05-16 00:29
Based on [this response](https://github.com/flutter/flutter/issues/82625#issuecomment-841725428) from @stuartmorgan, **this is an issue in this plugin**, not Flutter:

> > Since application:didReceiveLocalNotification is a method not recommended by the native side
> 
> Starting in iOS 10.
> 
> > remove support on newer flutter versions
> 
> Flutter supports [back to iOS 8](https://flutter.dev/docs/development/tools/sdk/release-notes/supported-platforms#supported-platforms). The replacement doesn't exist until iOS 10, so it cannot be removed without breaking everyone's apps on iOS 8 and iOS 9.
> 
> If I'm reading the linked issue correctly, a plugin is unconditionally logging error messages if an application implements a delegate method even though doing so is:
> 
> * still necessary on iOS 8 and 9
> * harmless in later versions.
> 
> That's a bug in the plugin, not Flutter.

**Comment by Jeasmine** [comment] 2021-05-17 21:59
> Based on [this response](https://github.com/flutter/flutter/issues/82625#issuecomment-841725428) from @stuartmorgan, **this is an issue in this plugin**, not Flutter:
> 
> > > Since application:didReceiveLocalNotification is a method not recommended by the native side
> > 
> > 
> > Starting in iOS 10.
> > > remove support on newer flutter versions
> > 
> > 
> > Flutter supports [back to iOS 8](https://flutter.dev/docs/development/tools/sdk/release-notes/supported-platforms#supported-platforms). The replacement doesn't exist until iOS 10, so it cannot be removed without breaking everyone's apps on iOS 8 and iOS 9.
> > If I'm reading the linked issue correctly, a plugin is unconditionally logging error messages if an application implements a delegate method even though doing so is:
> > 
> > * still necessary on iOS 8 and 9
> > * harmless in later versions.
> > 
> > That's a bug in the plugin, not Flutter.

Yeah, the problem is that OneSignal detects when the `- (void)application:(UIApplication*)application didReceiveLocalNotification:(UILocalNotification*)notification` method is being implemented. Since the AppDelegate used by Flutter implements it, please check under https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm, OneSignal returns the WARNING that you are seeing. The main intention is to alert the user not to use the deprecated method. Until Flutter internally supports it, OneSignal will keep launching the Warning. I hope this clarifies the problem.

**Comment by maxlapides** [comment] 2021-05-17 22:07
@Jeasmine I'm sorry but I have to insist that **this is an open issue in this plugin** that can and should be resolved by OneSignal.

This plugin should NOT print this warning to the console. Instead, it should detect which version of iOS the app is running on, handle this method on iOS 8 and 9, and handle it properly with the new API for newer versions of iOS.

**Comment by stuartmorgan** [comment] 2021-05-17 23:23
> Until Flutter internally supports it

What is the "it" that you believe Flutter does not support here?

I don't understand why you are trying to frame this as a bug in Flutter.

**Comment by Jeasmine** [comment] 2021-05-18 19:23
Hey @stuartmorgan, Sorry for the misunderstanding, I just wanted to explain what the log is trying to say. It is not a bug under Flutter, but because they support and implement the method `- (void)application:(UIApplication*)application didReceiveLocalNotification:(UILocalNotification*)notification` OneSignal detects it and prints the Warning even if your app is not using it. We are currently defining how to solve this in a more generic way to impact all wrappers. In the meantime, we keep encouraging not to use that method.

**Comment by xirainfotech** [comment] 2021-05-29 11:40
Any update on this?

**Comment by AmbujaAK** [comment] 2021-10-02 03:32
Any update??

**Comment by LocaTrackGitHub** [comment] 2021-11-25 07:10
Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
VERBOSE: Initializing the OneSignal Flutter SDK (2.2.0)

**Comment by dgilperez** [comment] 2021-12-14 13:57
Any updates @Jeasmine ?

**Comment by foveradm** [comment] 2022-04-12 05:10
Any updates @Jeasmine ?

**Comment by NurRozikin** [comment] 2022-07-23 02:46
I did uncomment and changed "platform :ios, '10.12'" in Podfile file (/iOS/podfile). Warning message not showing.

**Comment by mHassan20896** [comment] 2022-08-08 10:37
Is there any fix for this? I am using Flutter version 1.20 and I am not receiving notification on iOS device

**Comment by anmolgupta321** [comment] 2023-04-27 06:50
Flutter version: 3.7.12
onesignal_flutter 3.5.1
I am also getting same warnings
`2023-04-27 12:08:58.568676+0530 Runner[17201:195467] WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
`
Also i am not able to receive any notification on iOS, is this warning is responsible for not receiving any notification.
When i send a push notification to iOS devices, the device is getting registered with 'APNs BAD DEVICE TOKEN' along with this no notification is received on iOS simulator.
Any possible solution for this issue?

**Comment by nan-li** [comment] 2023-04-27 07:22
Hi all, I apologize for the delayed response but we don't have an update on the removal of this warning. 

This warning is issued by the OneSignal native iOS SDK due to some detection related to Flutter and **can be safely ignored** when using our Flutter SDK.

@mHassan20896 Is your error resolved or still happening for you?

@anmolgupta321 This warning can be safely ignored. The  'APNs BAD DEVICE TOKEN' is a separate issue, and may be because you are using an iOS simulator. Push notifications are generally not supported on simulators so it is best to test with a physical device. We will be able to support simulator push notifications in this SDK soon.

**Closed** 2024-03-22 21:49 UTC
Labels: Help Wanted, Low Priority

**Comment by nan-li** [comment] 2024-05-09 18:16
Hi @Selingungor90, if you are not calling that method yourself, it can be ignored. 
It is a warning that the OneSignal iOS SDK detects in the Flutter codebase. This does not mean Flutter SDK is calling the method, but that it exists.
