### ISSUE TITLE
Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99] , project :app > com.onesignal:OneSignal:3.12.7

### ISSUE THREAD

**Issue by basha97** [OneSignal/OneSignal-Flutter-SDK#225] opened 2020-04-03 07:05 UTC
**Description:**

My app has been building successfully . Today, suddenly i can't able to run failed with an exception .
This problem occurs last 15 days ago , i solved it by updating dependencies but now it's not working:
dependencies {
   // (OLD) implementation 'com.onesignal:OneSignal:3.11.4, 3.99.99'
    implementation 'com.onesignal:OneSignal:3.12.7'
}

(your description here)

**Environment**

onesignal_flutter: ^2.3.4

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99].
     Required by:
         project :app > com.onesignal:OneSignal:3.12.7
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Could not list versions using M2 pattern 'https://jcenter.bintray.com/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/'.
                  > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by jkasten2** [comment] 2020-04-07 18:27
@basha97 JCenter does not host Google Libraries, make sure your `build.gradle` files have `google()` before `jcenter()`. Normally you just have to check `android/build.gradle`. It should look like this.
https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/2.3.4/android/build.gradle#L15-L20

2nd to prevent future issues remove `implementation 'com.onesignal:OneSignal:3.12.7'` from your `android/build.gradle`
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/221#issuecomment-603121893

**Comment by jkasten2** [comment] 2020-04-07 18:28
This is a duplicate of #227, just with a different Google library.

**Closed by jkasten2** 2020-04-07 18:28 UTC
