### ISSUE TITLE
when app is teminated , we can received the notification, but 【 OneSignal.shared         .setNotificationOpenedHandler】 cannot be executed

### ISSUE THREAD

**Issue by wangxingxing123654** [OneSignal/OneSignal-Flutter-SDK#337] opened 2021-02-01 07:32 UTC
**Description:**

when app is teminated , we can received the notification, but 【 OneSignal.shared         .setNotificationOpenedHandler】 cannot be executed

**Comment by MeAtPros** [comment] 2021-03-26 12:08
I got this error "remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification"

**Comment by rodruiz** [comment] 2021-08-31 21:10
> I got this error "remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification"

Got the same message.

**Comment by agarwalrohit2503** [comment] 2021-09-16 09:39
Any fixes to this problem ?

**Comment by wrteam02** [comment] 2021-11-18 11:16
Got the same message.
-----------------------
remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification

**Comment by andredealmei** [comment] 2021-12-30 01:08
same here

**Comment by syahnurizal** [comment] 2022-02-09 13:02
Having the same issue. anyone found a solution for this?

**Comment by apoorvpandey0** [comment] 2022-03-05 16:09
Same issue

**Comment by esentis** [comment] 2022-04-04 13:25
Any updates on that ?

**Comment by emawby** [comment] 2022-06-24 17:25
Closing as a duplicate of #540 which has more recent discussion

**Closed by emawby** 2022-06-24 17:25 UTC

**Comment by emmadedayo** [comment] 2022-06-30 17:25
remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification
who can help with this?
