### ISSUE TITLE
 Problem with setNotificationWillShowInForegroundHandler

### ISSUE THREAD

**Issue by hugoyair** [OneSignal/OneSignal-Flutter-SDK#501] opened 2021-11-01 21:46 UTC
One signal_flutter version: 3.2.3

Description: 
I´m using one signal and everything is ok, but I was wondering why sometimes when I´m into an application, notification show it and enter to : 

OneSignal.shared.setNotificationOpenedHandler()

When It should enter to: 

setNotificationWillShowInForegroundHandler()

It sometimes fail not always, I mean notification come always.

**Comment by jkasten2** [comment] 2021-11-09 19:08
@hugoyair Thanks for reporting. Could share a step by step of reproducing the issue? It isn't clear to me if the issue is with `setNotificationOpenedHandler` or `setNotificationWillShowInForegroundHandler` in your app.

Could you also let us know if the is an issue on Android or iOS? Also please note the Android / iOS version and device model as well.

**Comment by hugoyair** [comment] 2021-11-09 21:31
I´m sorry I don´t speak English, I said that I have a problem with setNotificationWillShowInForegroundHandler() when my phone app is focus (into the app) (foreground), should listen the handler (setNotificationWillShowInForegroundHandler()) but tI doesn´t come.   But it fails sometimes, not always.

**Comment by hugoyair** [comment] 2021-11-09 21:32
Android 10 versión 
Huawei p40 lite 
Huawei p30 lite
Xiaomi redmi note 9

**Comment by nan-li** [comment] 2021-11-18 20:51
Hi @hugoyair, I see you posted a lot of details at https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/509 so I will close this for now and follow up on the other issue.

**Closed by nan-li** 2021-11-18 20:51 UTC
