### ISSUE TITLE
[Bug]: OneSignal not detect granted permission from other plugin on Android

### ISSUE THREAD

**Issue by edisonlsm** [OneSignal/OneSignal-Flutter-SDK#827] opened 2024-01-26 14:32 UTC
### What happened?

When requesting the notification using another plugin, OneSignal on Android 13+ does not recognize that the app already has notification permission without calling requestPermission().

### Steps to reproduce?

```Markdown
1. Init OneSignal with the App ID.
2. The subscription shows up on the dashboard when you install the app.
3. Request notification permission using other code/other plugin and not OneSignal itself (i.e., permission_handler) and grant the permission.
4.1. On iOS, the subscription permission status updates automatically to "granted" on dashboard.
4.2. On Android, the subscription permission status stays as "Not granted" until I call the requestPermission() method from OneSignal SDK.
```

### What did you expect to happen?

I expected OneSignal to detect on Android 13+ when the permission was granted, as it does today on iOS.

### OneSignal Flutter SDK version

5.0.4

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2024-12-06 23:39
Hello there--apologies that this issue was missed. Since it's been quite some time since this was originally reported, I'm going to close this issue.

If you are still having problems on the latest version of the SDK, please open a new issue with [debug logs](https://documentation.onesignal.com/docs/capturing-a-debug-log) reproducing this behavior.

Thanks!

**Closed by jennantilla** 2024-12-06 23:39 UTC
